$script_mysql = <<-SCRIPT
	apt-get update && \
	apt-get install -y mysql-server-5.7 && \
	mysql -e "create user 'phpuser'@'%' identified by 'pass';" 
SCRIPT

$script_puppet = <<-SCRIPT2
	apt-get update
	apt-get install -y puppet
SCRIPT2

$script_nginx = <<-SHELL
	apt-get update
	apt-get install -y nginx
SHELL

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  
  config.vm.define "mysqldb" do |mysqldb|

	#host-only private network
	mysqldb.vm.network "private_network", ip: "192.168.56.5"

	#interface as local bridge dhcp - vagrantup.com/docs/networking/public_network
	#mysqldb.vm.network "public_network"

	# forward port if NAT enabled
	#mysqldb.vm.network "forwarded_port", guest: 80, host: 8080

	#mysqldb.vm.provision "shell", inline: $script_nginx

	mysqldb.vm.provision "shell", inline: $script_mysql

	mysqldb.vm.provision "shell", inline: "cat /config/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
	mysqldb.vm.provision "shell", inline: "service mysql restart"

	mysqldb.vm.synced_folder ".", "/vagrant", disabled: true
	mysqldb.vm.synced_folder "./config", "/config"
	
  end

  config.vm.define "phpweb" do |phpweb|
	phpweb.vm.network "forwarded_port", guest:80, host:8089
	phpweb.vm.network "private_network", ip: "192.168.56.10"
	
	#phpweb.vm.network "public_network", ip: "192.168.56.10"
	
	phpweb.vm.provision "shell", inline: $script_puppet
	
	phpweb.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "./config/manifests"
		puppet.manifest_file = "phpweb.pp"
	end
  end
  
end