---
- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Baixar o arquivo de instalacao do Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
        mode: 0644

    - name: 'Descompactar o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
        owner: www-data
        group: www-data
      become: yes

    - name: 'Copiar o arquivo de configuração do wordpress'
      copy:
        src: "{{ wp_installation_dir }}/wp-config-sample.php"
        dest: "{{ wp_installation_dir }}/wp-config.php"
        owner: www-data
        group: www-data        
        remote_src: yes
      become: yes

    - name: 'Configurar o wp-config com as entradas do banco de dados'     
      replace:
        path: "{{ wp_installation_dir }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
        - { regex: 'username_here', value: "{{ wp_username }}"}
        - { regex: 'password_here', value: "{{ wp_user_password }}"}
        - { regex: 'localhost', value: "{{ wp_db_host_ip }}"}
      become: yes

 #   - name: 'Copiar a configuracao do Apache para servir o Wordpress'
 #     copy:
 #      src: 'files/000-default.conf'
 #      dest: '/etc/apache2/sites-available/000-default.conf'
 #      backup: yes
 #     become: yes
 #     notify:
 #       - restart apache

    - name: 'Configurar o Apache para servir o Wordpress'
      replace:
        path: '/etc/apache2/sites-available/000-default.conf'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: '/var/www/html', value: "{{ wp_installation_dir }}" }
      become: yes
      notify:
        - restart apache