Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  #config.ssh.private_key_path = "chave privada"
  #config.ssh.host = "172.17.177.40"
  #config.ssh.port = 22

  config.vm.provider "virtualbox" do |v|
     v.memory = 1024
  end

  config.vm.define "mysql" do |m|
    m.vm.network "private_network", ip: "192.168.56.110"

    m.vm.provider "virtualbox" do |v|
       v.memory = 1024
       v.name = "mysqldb"
    end

    m.vm.provision "ansible" do |ansible|
      ansible.playbook = "play-00-install-mysql.yaml"
    end

  end 

  config.vm.define "wordpress" do |m|
    m.vm.network "private_network", ip: "192.168.56.100"

    m.vm.provider "virtualbox" do |v|
       v.memory = 512
       v.name = "wordpress"
    end
    
    m.vm.provision "ansible" do |ansible|
      ansible.playbook = "play-01-install-php-apache.yaml"
    end
    
    m.vm.provision "ansible" do |ansible|
      ansible.playbook = "play-02-wordpress.yaml"
    end
  end

end
