---
- hosts: all
  tasks:
    - name: 'Instalar Apache2, Mysql5.7 e Php7.2'
      apt:
        update_cache: yes  #apt update
        cache_valid_time: 3600 #1 hora
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php7.2
        - apache2
        - libapache2-mod-php7.2
        - php7.2-gd
        - php-ssh2
        - mysql-server-5.7
        - python3-mysqldb
        - php7.2-mysql
        - ghostscript
        - libapache2-mod-php
        - php-bcmath
        - php-curl
        - php-imagick
        - php-intl
        - php-json
        - php-mbstring
        - php-mysql
        - php-xml
        - php-zip        