---
- hosts: all
  tasks:
    - name: 'Instalar o PHP7'
      # equiv.: sudo apt install php7.2 -y
      apt:
        name: php7.2
        state: latest
      become: yes
    - name: 'Instalar o Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Instalar o modphp'
      apt:
        name: libapache2-mod-php7.2
        state: latest
      become: yes