$script_puppet = <<-SCRIPT
	apt-get update
	apt-get install -y puppet
SCRIPT

Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/bionic64"
	
	config.vm.define "mysqlserver" do |mysqlserver|
		mysqlserver.vm.network "private_network", ip: "192.168.56.5"
		
		#copia a chave publica para o servidor mysql
		#criar keys: ssh-keygen -t rsa -f id_bionic
		mysqlserver.vm.provision "shell", 
		 	inline: "cat /vagrant/config/id_bionic.pub >> .ssh/authorized_keys"
	end
  
	config.vm.define "phpweb" do |phpweb|
		phpweb.vm.network "forwarded_port", guest:80, host:8089
		phpweb.vm.network "private_network", ip: "192.168.56.10"

		phpweb.vm.provision "shell", inline: $script_puppet

		phpweb.vm.provision "puppet" do |puppet|
			puppet.manifests_path = "./config/manifests"
			puppet.manifest_file = "phpweb.pp"
		end
	end	
	
	config.vm.define "ansible" do |ansible|
	    ansible.vm.network "private_network", ip: "192.168.56.25"

	    #copia a chave privada para  o ansible
	    ansible.vm.provision "shell", 
			inline: "cp /vagrant/config/id_bionic /home/vagrant/id_bionic && \
			chmod 600 /home/vagrant/id_bionic && \
			chown vagrant.vagrant /home/vagrant/id_bionic"
		
		#instala o ansible
	    ansible.vm.provision "shell",
	        inline: "apt-get update && \
	                 apt-get install -y software-properties-common && \
	                 apt-add-repository --yes --update ppa:ansible/ansible && \
	                 apt-get install -y ansible"

		ansible.vm.provision "shell",
			inline: "ansible-playbook -i /vagrant/config/ansible/hosts /vagrant/config/ansible/playbook.yml"

		#ansible.vm.provision "ansible" do |ansible|
		#	ansible.inventory_path = "config/ansible/hosts"
		#	ansible.playbook = "config/ansible/playbook.yml"

		end
  	
	end	

end