Vagrant.configure("2") do |config|

  config.vm.box = "Microsoft/EdgeOnWindows10"

  config.vm.network "private_network", ip: "192.168.56.200"

  # config.vm.network "public_network", ip: "192.168.56.110"

  # config.vm.synced_folder "../data", "/vagrant_data"

    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
    
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.name = "Windows-10-Vagrant"
    end

#    config.vm.provision "ansible" do |ansible|
#      ansible.playbook = "play-00-install-mysql.yaml"
#    end

end
